name: Earthquake Data

on:
  schedule:
    - cron: '*/20 * * * *'  # Menjalankan setiap 5 menit
  push:
    branches:
      - main  # Menjalankan workflow setiap kali ada commit di branch utama

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests pandas SQLAlchemy python-dotenv matplotlib basemap instagrapi pillow

    - name: Run main script
      run: python main.py
